### ISSUE TITLE
error: can't copy 'vissim_v8\default\default.inpx': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by davidtweaver** [brianhuey/vissim#1]
I'm trying to install this on MacOS Sierra, (by running sudo python setup_v8.py install) and I get the above error. Any ideas what I'm doing wrong?

**Comment by brianhuey** [comment]
Which version of Python are you running?

**Comment by davidtweaver** [comment]
Python 2.7

**Comment by brianhuey** [comment]
Try to pull the latest commit and see if that works. I think it was just that the path has to be written using forward slashes rather than back slashes which I had fixed in another branch but forgot to push to github.
